services:
  app:
    image: nguyengiathuy/recipe-app-api:1.0.0
    container_name: recipe-app-api
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: recipe-app-db
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD

volumes:
  dev-db-data:
  dev-db-static-data:
